### PR TITLE
refactor: Add Values matcher class

### PR DESCRIPTION
**Pull request by tienvx**
The matcher is defined at https://github.com/pact-foundation/pact-specification/tree/version-4#supported-matching-rules

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
There are over 20 of these. Would you mind adding a bit more detail, or perhaps letting me know expected order or priority?

Some of these feel like things I may have approved before.

**Comment by tienvx** [comment]
* There are 12 classes for generators.
  * You **reviewed all** of them.
  * I removed `jsonSerialize` methods for all of them. Look like they are not needed.
* There are 23 classses for matchers.
  * You **reviewed 2** of them (`Equality` and `Regex`).
  * The method `jsonSerialize` is required for these classes to work.
  * You can review the pull request in **any order.** There are 2 notes:
    * It also applied to pull requests with **failed test case**
    * Only **one exception**:
      * First `Date` #394, then
        * `Time` #395
        * Or `DateTime` #396
  * If the class extends `GeneratorAwareMatcher`, you can see that class here https://github.com/pact-foundation/pact-php/pull/391/files#diff-bb4df63ac65cc79b12dfada6442c909439b9f92b26bdd54a197cdd5237cdc84c

**Review by Lewiscowles1986 — APPROVED** [review]

**Comment by Lewiscowles1986** [comment]
Do you think once these merge you might be able to write up a sample usage difference of before and after?

**Comment by tienvx** [comment]
I already prepare examples (also act as integration tests) for:
* [matchers](https://github.com/pact-foundation/pact-php/tree/ffi/example/matchers)
* [generators](https://github.com/pact-foundation/pact-php/tree/ffi/example/generators)

Once all PRs are merged, I expect there will be **no** difference for users to use them.

**Pull request merged**
