### PR TITLE
Use Rust FFI #3.2: Default port zero

### PR DESCRIPTION
**Pull request by tienvx**
Depend on https://github.com/pact-foundation/pact-php/pull/280

### CODE REVIEW

**Comment by YOU54F** [comment]
Yep totally in agreement that defaulting to port 0 and therefore allowing the rust core to try and find an available port, would be the preferred behaviour for all users, with them otherwise having the option to select their own

**Review by YOU54F — APPROVED** [review]
I would in agreement that a default port zero is a very sensible default, the core try and find an available port

**Comment by YOU54F** [comment]
merged in #323 

https://github.com/pact-foundation/pact-php/commit/2706eff5680078f4c43dfb28dd6ee6b92d44ec48

**Comment by tienvx** [comment]
Close as there will be a PR from `ffi` to `master`

**Pull request closed without merging**
