### PR TITLE
Added warning log in case of validation failure.

### PR DESCRIPTION
**Pull request by siad007**
Added warning log with stderr in case of validation failure.

### CODE REVIEW

**Comment by cfmack** [comment]
@siad007 , can you run the following to pass the lint checks and resubmit:
php .\vendor\tm\tooly-composer-script\bin\php-cs-fixer.phar fix --config .php_cs

**Comment by cfmack** [comment]
I won't be able to get to the PR until at least next week.

**Comment by siad007** [comment]
@cfmack done

**Comment by cfmack** [comment]
Sweet!

**Pull request merged**
