### PR TITLE
Allow PHP8

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
I am not sure why it fails on windows. Any idea?

**Comment by Jurigag** [comment]
@cfmack What i need to do for you to accept this?

**Comment by eiriarte-mendez** [comment]
> I am not sure why it fails on windows. Any idea?

Hi @Jurigag , I was at the same point 3 days ago.... since running on linux seems not to be a problem, Im installing my fork for now... but would be great if the problem can be fixed and PR merged...

I think the problem is the handling with `resource` handles in php8(https://php.watch/versions/8.0#resource-object):
```
TypeError: fclose(): supplied resource is not a valid stream resource
```
... Im not completely sure though

**Comment by cfmack** [comment]
@eiriarte-mendez is right.  It looks to be the same error as seen.   If you want to try to ramp up the Amp dependency versions to see if that fixes it (and Amp)

```
#1 D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php(201): Amp\Process\Internal\Windows\Runner->free(Object(Amp\Process\Internal\Windows\Handle))

#2 D:\a\pact-php\pact-php\vendor\amphp\process\lib\Process.php(85): Amp\Process\Internal\Windows\Runner->destroy(Object(Amp\Process\Internal\Windows\Handle))
#3 [internal function]: Amp\Process\Process->__destruct()
#4 {main}
  thrown in D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php on line 221
Fatal error: Uncaught TypeError: fclose(): supplied resource is not a valid stream resource in D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php:221
Stack trace:
#0 D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php(221): fclose(Resource id #2730)
#1 D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php(201): Amp\Process\Internal\Windows\Runner->free(Object(Amp\Process\Internal\Windows\Handle))
#2 D:\a\pact-php\pact-php\vendor\amphp\process\lib\Process.php(85): Amp\Process\Internal\Windows\Runner->destroy(Object(Amp\Process\Internal\Windows\Handle))
#3 [internal function]: Amp\Process\Process->__destruct()
#4 {main}
  thrown in D:\a\pact-php\pact-php\vendor\amphp\process\lib\Internal\Windows\Runner.php on line 221
```

**Comment by floflock** [comment]
@Jurigag is there an update maybe? :)

**Comment by Jurigag** [comment]
@floflock honestly we just made a fork for our internal usage, not sure what's a problem here, we don't use windows anyway

**Comment by cfmack** [comment]
I believe this was resolved on another PR

**Pull request closed without merging**
