### PR TITLE
feat: Support matchers in path

### PR DESCRIPTION
**Pull request by turb0bur**
Added matchers support in the ConsumerRequest path in order to use path variables

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
I Like this 👍

**Comment by cfmack** [comment]
I kicked off the CI.  Lint checks failed: [7.3 Lint](https://github.com/pact-foundation/pact-php/runs/7599360533?check_suite_focus=true)

**Comment by Lewiscowles1986** [comment]
Notice it doesn't give any helpful errors about how that file fails lint...

On second glance, this does widen a lot of interfaces; which might be problematic for consumers. Might be worth giving it a go-over with phpstan and running the unit suite.

**Comment by cfmack** [comment]
Closed in #273

**Pull request merged**
