### PR TITLE
Get rid of additional dependency for windows.

### PR DESCRIPTION
**Pull request by siad007**
No need to handle windows differently. WDYT?

### CODE REVIEW

**Comment by cfmack** [comment]
Windows tests failed: https://ci.appveyor.com/project/mattermack/pact-php/builds/35809330

**Comment by siad007** [comment]
hm that is strange. It is just working fine on my windows.
Would you mind to restart the appveyor build, just to make sure it is not something else:
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]                                 
  The process "phpunit --debug -c example/phpunit.all.xml" exceeded the timeout of 300 seconds.
```

**Comment by cfmack** [comment]
I kick started https://ci.appveyor.com/project/mattermack/pact-php/builds/35818017

Other Windows builds you have recently submitted passed.

**Comment by cfmack** [comment]
Stopping Process Id: 2188
Test 'PhpPact\Standalone\MockService\Service\MockServerHttpServiceTest::testDeleteAllInteractions' started
[2020-10-18T21:04:03.571155+00:00] server.DEBUG: start background command: C:\projects\pact-php\src\PhpPact\Standalone\Installer/../../../..\pact\bin\pact-mock-service.bat service --consumer="someConsumer" --provider="someProvider" --pact-dir=".\example\output\\" --pact-file-write-mode=overwrite --host=localhost --port=7200 --cors=true --pact-specification-version=2.0.0 [] []
[2020-10-18T21:04:03.578100+00:00] server.DEBUG: started process pid=5088 [] []
                                                                                                 
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                 
  The process "phpunit --debug -c example/phpunit.all.xml" exceeded the timeout of 300 seconds.  
                                                                                                 
Again, same failure (good thing, right ;))

**Comment by cfmack** [comment]
We're testing on Windows on AppVeyor on 7.2.1

https://github.com/pact-foundation/pact-php/blob/master/appveyor.yml

**Comment by siad007** [comment]
I will close this PR because it is now reproducable not working.

**Pull request closed without merging**
