### PR TITLE
test(compatibility-suite): Fix compatibility suite v1 hang

### PR DESCRIPTION
**Pull request by tienvx**
I think recent update to pact broker `2.115` or `2.116` cause pact broker to hang. Move to `2.114` a month ago solve the issue

### CODE REVIEW

**Comment by YOU54F** [comment]
So it is an issue that was affecting aarch64 images with sqlite since we initially built them, but is affecting x86_64 images too, since we updated the alpine image to 3.19.

tracking issue  https://github.com/pact-foundation/pact-broker-docker/issues/148

**Review by YOU54F — APPROVED** [review]

**Comment by YOU54F** [comment]
thanks for the heads up @tienvx

**Comment by YOU54F** [comment]
Fix for sqlite in pact-broker has been merged and will be released shortly

https://github.com/pact-foundation/pact-broker-docker/pull/166

**Comment by YOU54F** [comment]
Released and all sorted, have re-ran the failing jobs and they are all passing now. We will want to get some tests in pact-broker that utilise sqlite as part of the test run (it currently just runs against pg for integration tests)

**Comment by tienvx** [comment]
Look like it's fixed in `2.117`. So we can close this PR. It's no longer needed. Thank @YOU54F  for fixing.

**Comment by tienvx** [comment]
Look like it happen again on `2.118`

**Comment by tienvx** [comment]
Reopened, updated to `2.117` and merged

**Comment by YOU54F** [comment]
thanks Tien, sorry the latest image has gone out with a bug, am sorting it ( reverting a pr ) and will get it out shortly

**Comment by YOU54F** [comment]
@tienvx there is a new release now so this should be solved

**Pull request merged**
