### PR TITLE
feat: Use Rust FFI

### PR DESCRIPTION
**Pull request by tienvx**

### CODE REVIEW

**Comment by tienvx** [comment]
Something wrong with the CI:
* It should only run on `7.4` and `8.0`, but it also run on `7.3`
* Linter is warning about code on `master`, not code from this branch, because this issue is already fixed on this branch:

```
diff --git a/src/PhpPact/Consumer/Model/ConsumerRequest.php b/src/PhpPact/Consumer/Model/ConsumerRequest.php
index 9fe9d22..1e2732d 100644
--- a/src/PhpPact/Consumer/Model/ConsumerRequest.php
+++ b/src/PhpPact/Consumer/Model/ConsumerRequest.php
@@ -94,8 +94,8 @@ class ConsumerRequest implements \JsonSerializable
     }
 
     /**
-     * @param string         $header
-     * @param array | string $value
+     * @param string       $header
+     * @param array|string $value
      *
      * @return ConsumerRequest
      */
diff --git a/src/PhpPact/Consumer/Model/ProviderResponse.php b/src/PhpPact/Consumer/Model/ProviderResponse.php
index dd22f88..a9f9dee 100644
--- a/src/PhpPact/Consumer/Model/ProviderResponse.php
+++ b/src/PhpPact/Consumer/Model/ProviderResponse.php
@@ -64,8 +64,8 @@ class ProviderResponse implements \JsonSerializable
     }
 
     /**
-     * @param string         $header
-     * @param array | string $value
+     * @param string       $header
+     * @param array|string $value
      *
      * @return ProviderResponse
      */

```

**Comment by cfmack** [comment]
Wow, moving to Rust is huge!  How can I assist as I see the CI is not passing.

**Comment by tienvx** [comment]
Still problems in my comment above. I think CI is cached so it always run against `master` branch. I don't know how to fix from my side.

**Comment by mefellows** [comment]
(I've just hit approve @tienvx to run your build)

**Comment by tienvx** [comment]
@cfmack I fixed the conflict, please take a look again

**Comment by tienvx** [comment]
Your merge commit has syntax error ce65785. I re-based and forced push anyway. New code support specification v4.0 . Tests will not be passed until version 0.1.3 of FFI library is released. But the code is ready to be reviewed.

Question: Do we need a new branch 8.x on this repository?

**Comment by tienvx** [comment]
Updated Pact FFI library to 0.1.3 . Tests will be passed when approve.

**Comment by tienvx** [comment]
@cfmack In case you haven't seen this comment on Slack yet https://pact-foundation.slack.com/archives/C9W94PXPY/p1646321219144749

**Comment by tienvx** [comment]
Closed as split into smaller pull requests.

**Pull request closed without merging**
