### PR TITLE
feat: add consumer version selectors support

### PR DESCRIPTION
**Pull request by jameshalsall**

### CODE REVIEW

**Comment by jameshalsall** [comment]
Workflow failures look unrelated to these changes 🤔

**Comment by jameshalsall** [comment]
Having tested this, I think there is something missing. It seems like the PHP SDK is just grabbing the latest version of each consumer and passing that to the `pact-provider-verifier`, instead of auto-discovering the versions based on the tags provided. This is probably my lack of understanding of how the internals of the SDK are put together 🤔

**Comment by jameshalsall** [comment]
We have this working now for our pipelines 👍🏻  open to suggestions/feedback

**Comment by bethesque** [comment]
Is it possible to make the selectors just plain maps (or what ever the equivalent is in php), and pass them through unchanged to the pacts for verification API? The problem with hardcoding they keys is that every time we make a new selector in the Pact Broker (and there will be a bunch more coming soon), the developers using the client libraries can't use them until a new version of the client library is released.

**Comment by bethesque** [comment]
I'd really prefer the client libraries didn't implement any local validation of the selectors, because that validation logic is likely to change. For example, when the api was first released, it didn't support all pacts for a given tag, and now it does. The error response that is returned from a request with invalid selectors should be displayed to the user instead.

**Comment by jameshalsall** [comment]
understood, that makes sense 👍🏻  I will remove the modelling of the consumer version selectors, and model them as strings instead, then let the `pact-provider-verifier` handle the erroring

**Comment by bethesque** [comment]
Excuse my ignorance, but are there no hashes/maps in php?

**Comment by jameshalsall** [comment]
No, arrays can be used as a map but they are not true maps with constant time lookups etc. 

We can create a custom class to represent the version selectors, which would be like a collection. That's probably more idiomatic in PHP.

**Comment by bethesque** [comment]
Cool. I have nothing more to add, as my knowledge of php is exactly 0! Thanks.

**Comment by jameshalsall** [comment]
Any update on merging this?

The workflow failures look unrelated to anything in this PR.

**Comment by bethesque** [comment]
Maybe request a review? I have the permissions to hit the merge button, but I'm not one of the maintainers of pact-php, and don't feel qualified to make a call on it.

**Comment by mefellows** [comment]
@siad007 would you be up for reviewing this PR?

**Review by siad007 — APPROVED** [review]
LGTM 😃

**Comment by siad007** [comment]
@mefellows there are some code style issues https://github.com/pact-foundation/pact-php/pull/204/checks?check_run_id=2856392414 - this should be fixed

**Review by siad007 — CHANGES_REQUESTED** [review]
Please cleanup the code style issues found https://github.com/pact-foundation/pact-php/pull/204/checks?check_run_id=2856392414

**Review by siad007 — APPROVED** [review]
Ahh - sry but now i read the rest of the conversation :) code looks good to me and of course the phpcs could be ignored by now.

**Comment by cfmack** [comment]
Code looks good.  Can you merge the CI changes from Master and get a passing build?

**Comment by jameshalsall** [comment]
Sorry, missed your last messages. I've merged latest master into this branch now.

**Comment by jameshalsall** [comment]
Of course, did not help :) I am not sure how you have the phpcs stuff set up, maybe it's pulling a remote ruleset that is changing? `master` branch CI passed on its last commit 🤔

**Comment by Loyen** [comment]
@jameshalsall Looks like the linter fails. Could you run `composer run fix` to let php-cs-fixer try to resolve them?

**Comment by jameshalsall** [comment]
This is a CI problem, it's fine on my local machine:

```
➜  pact-php git:(add-consumer-version-selectors) composer lint
> php-cs-fixer fix --config .php-cs-fixer.php --dry-run
You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!

Loaded config default from ".php-cs-fixer.php".

Checked all files in 1.464 seconds, 14.000 MB memory used
➜  pact-php git:(add-consumer-version-selectors) echo $?
0
```

**Comment by cfmack** [comment]
Completed as part of #213

**Pull request closed without merging**
