### PR TITLE
Use Rust FFI #5: Provider

### PR DESCRIPTION
**Pull request by tienvx**
This is 5th pull request in a series of "small" pull requests I split from https://github.com/pact-foundation/pact-php/pull/210

This pull request depend on https://github.com/pact-foundation/pact-php/pull/281, please review it first.

### CODE REVIEW

**Comment by tienvx** [comment]
I gave up trying to find the cause and solution for the weird problem that make tests failed on Windows Server 2022 - Github Actions (it doesn't happen on Windows 11 on my local machine). Because it doesn't happen to my local machine, it's really hard to replicate it.

All I know is something wrong happen with `amphp/process` .

Here is the error:

```
Test 'PhpPactTest\Standalone\StubServer\Service\StubServerHttpServiceTest::testHealthCheck' started
[2023-05-06 06:13:12] server.DEBUG: start background command: D:\a\pact-php\pact-php\src\PhpPact\Standalone\Installer\Model/../../../../../bin/pact-ruby-standalone/bin/pact-stub-service.bat D:\a\pact-php\pact-php\tests\PhpPact\Standalone\StubServer\Service/../../../../_resources/someconsumer-someprovider.json --host=localhost --port=7201 [] []
[2023-05-06 06:13:12] server.DEBUG: started process pid=1644 [] []
Script phpunit --debug -c example/phpunit.core.xml handling the test event returned with error code -1073741819
```

I tried to replicate on a test project and I got similar issue:
```
[2023-05-06T11:25:54.203854+00:00] server.DEBUG: start background command: D:\a\test-memory-error-windows-server\test-memory-error-windows-server\src/../bin/pact-ruby-standalone/bin/pact-stub-service D:\a\test-memory-error-windows-server\test-memory-error-windows-server\src/../pacts/someconsumer-someprovider.json --host=localhost --port=7201 [] []
^CScript php src/standalone-first.php handling the standalone-first event returned with error code -1073741510
```

Here is that project https://github.com/tienvx/test-memory-error-windows-server (see latest pipeline). This problem **doesn't happen** with `symfony/process` (see latest commit where I replace `symfony/process` with `amphp/process` and the error appear).


If someone know what's going on and have a solution for it it would be great. For now can we just ignore the failed tests on Windows Server (until https://github.com/pact-foundation/pact-php/pull/284 is merged)?

**Comment by tienvx** [comment]
I'm able to make this PR green by lower number of seconds waiting for stub server (Ruby Standalone version). Not sure why we need to wait for [10 seconds](https://github.com/pact-foundation/pact-php/commit/81632b1587ad0f979cceadc0361fd3bac19a775a).

I'm still don't know what is the root cause for this error yet `error code -1073741819`

**Comment by YOU54F** [comment]
merged in #323 

https://github.com/pact-foundation/pact-php/commit/6aad4567b834b831babcf9e0af0ea2b10f5a96c5

**Comment by tienvx** [comment]
Close as there will be a PR from `ffi` to `master`

**Pull request closed without merging**
