### PR TITLE
test: Test FFI Client

### PR DESCRIPTION
**Pull request by tienvx**

### CODE REVIEW

**Review by Lewiscowles1986 — COMMENTED** [review]
These feel like useless changes. Would you mind explaining a little bit as to the value of this code?

**Comment by tienvx** [comment]
The purpose of this test is only to increase code coverage

**Comment by Lewiscowles1986** [comment]
Right but in this case it's nonsense coverage. If you were to run infection over this type of coverage it might still be low, because as one of the tests states, there are no assertions. We're simply expecting that calling something won't explode.

**Comment by tienvx** [comment]
Replaced `pactffi_string_delete` by `pactffi_check_regex` which return a result. Added an assertion to assert the result. Does it look a bit better?

**Review by Lewiscowles1986 — APPROVED** [review]

**Pull request merged**
