### PR TITLE
refactor: Add InteractionPart enum

### PR DESCRIPTION
**Pull request by tienvx**
This code will be used later

Use case:

```php
$driver->registerBody($interaction, InteractionPart::REQUEST);
$driver->registerBody($interaction, InteractionPart::RESPONSE);

public function registerBody(Interaction $interaction, InteractionPart $part): void
{
    $body = $part->isRequest() ? $interaction->getRequest()->getBody() : $interaction->getResponse()->getBody();
    ...
}
```

### CODE REVIEW

**Review by Lewiscowles1986 — COMMENTED** [review]
Can you let me know a little more about the intended use-case for this?

**Comment by Lewiscowles1986** [comment]
This feels like it's compensating for a lack of a getBody method, which should not care if the object is a request or a response.

**Comment by tienvx** [comment]
Added method `getBody` and `getHeaders` to `Interaction`

**Comment by tienvx** [comment]
Ping @Lewiscowles1986 . I think you miss this one

**Review by Lewiscowles1986 — APPROVED** [review]
Hey @tienvx I'll approve to unblock as I can't see any deep problems and I'd like to unblock you; but it likely still needs iteration. The enum, the use of match, are papering over design problems.

I was trying to work out how best to communicate without just writing code. I won't do that as it seemed like it might be obnoxious on my part.

**Comment by tienvx** [comment]
Thank you. If you have additional ideas please continue comment to this discussion

**Pull request merged**
