### PR TITLE
Consumer selection

### PR DESCRIPTION
**Pull request by jildertmiedema**
We had a problem with consumer filtering. Like https://github.com/pact-foundation/pact-php/issues/245. This is how we fixed it.

Not sure if it breaks other stuff.

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Quick thought: Any chance of a test to guard against regression?

**Comment by cfmack** [comment]
Tests did not fail.  However, I think we want to be able to set latest to false somewhere.

**Comment by YOU54F** [comment]
It should be opt-in by user not implicit, without an option to disable.

You should also add a test to cover your change

https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors#advanced

```
{ "tag": "<tag>" } - all versions with the specified tag
{ "tag": "<tag>", "latest": true }- the latest version for each consumer with the specified tag
```

This would change user facing behaviour where they previously fetched all pacts, by tag, but now only fetch the latest.

**Comment by tienvx** [comment]
Please change the target branch to `release/9.x`. I'm sorry about that.

**Comment by YOU54F** [comment]
Hey,

I am going to close down this PR, I apologise but I also don't think it is the right approach

> It should be opt-in by user not implicit, without an option to disable.

As an end user today, you can pass in your own selectors to solve use cases which will vary over time, and we should not provide filtering on the users behalf without them knowing.

Happy to reconsider, but I would say it would be worth describing your workflow and the issues you are facing, rather than just providing the solution, as in many cases there are probably better solutions (such as looking at your pact verification workflow and upgrading it to use named branches/environment selectors, over I assume tags) 

Thanks for proposing a change and hope this doesn't put you off in the future!

**Pull request closed without merging**
