### PR TITLE
Pin linux installer to latest PACT ruby standalone

### PR DESCRIPTION
**Pull request by lewiscowleschipuk**
Makes https://github.com/pact-foundation/pact-ruby-standalone/pull/73 available for pact-php

### CODE REVIEW

**Comment by lewiscowleschipuk** [comment]
I Have no idea what the problem is here. Anyone that can help?

**Comment by bethesque** [comment]
This URL will no longer work `https://test.pact.dius.com.au/` https://github.com/pact-foundation/pact-php/runs/6578085525?check_suite_focus=true#step:6:124

It needs to be updated to `https://test.pactflow.io` (same credentials).

**Comment by Lewiscowles1986** [comment]
thanks @bethesque https://github.com/pact-foundation/pact-php/pull/249 does this. I'd like to keep them separate for now. I can close this until that (or `master`) fixes and rebase.

**Comment by Lewiscowles1986** [comment]
Can someone close this now?

**Comment by Lewiscowles1986** [comment]
I no longer have access to the `lewiscowleschipuk` user

**Pull request closed without merging**
